apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bulk-import-test
  annotations:
    github.com/project-slug: test-org-pat/bulk-import-test
    backstage.io/managed-by-location: https://github.com/test-org-pat/bulk-import-test/tree/main/catalog-info.yaml
    backstage.io/source-location: https://github.com/test-org-pat/bulk-import-test/tree/main/
spec:
  type: other
  lifecycle: unknown
  owner: user:default/pataknight
